export const sideQuests = [
  {
    id: 'ruin_clearing',
    name: 'Clear the Old Watchtower',
    description: 'A ruined watchtower on the east road is infested with goblins. Clear them out to make the road safer.',
    objectives: [{ id: 'clear_goblins', description: 'Defeat goblins at the watchtower', target: 5 }],
  },
  {
    id: 'herb_hunt',
    name: 'Athelas for the Healer',
    description: 'A healer in the frontier settlement needs rare athelas herbs from the forest edge.',
    objectives: [{ id: 'gather_herbs', description: 'Gather athelas plants', target: 3 }],
  },
  {
    id: 'beast_hunt',
    name: 'Wolf Pack Menace',
    description: 'A pack of wolves has been attacking travelers near the old bridge. Thin their numbers.',
    objectives: [{ id: 'kill_wolves', description: 'Defeat wolves near the bridge', target: 4 }],
  },
  {
    id: 'crafting_commission',
    name: 'Tools for the Settlement',
    description: 'The frontier settlement needs stone tools. Craft and deliver pickaxes and axes.',
    objectives: [
      { id: 'deliver_pickaxes', description: 'Deliver stone pickaxes', target: 2 },
      { id: 'deliver_axes', description: 'Deliver stone axes', target: 2 },
    ],
  },
  {
    id: 'ore_prospecting',
    name: 'Iron for the Forge',
    description: 'The dwarven smiths need iron ore to repair their forge. Mine ore from the mountains.',
    objectives: [{ id: 'mine_iron', description: 'Mine iron ore', target: 10 }],
  },
  {
    id: 'ruin_clearing_2',
    name: 'The Haunted Barrow',
    description: 'An ancient barrow mound has awakened wights. Cleanse the site before corruption spreads.',
    objectives: [{ id: 'defeat_wights', description: 'Defeat wights in the barrow', target: 3 }],
  },
  {
    id: 'beast_hunt_spider',
    name: 'Spider Nest in Mirkwood',
    description: 'Giant spiders have woven webs across a forest path. Destroy them and clear the way.',
    objectives: [{ id: 'kill_spiders', description: 'Defeat spiders', target: 6 }],
  },
  {
    id: 'herb_hunt_mushroom',
    name: 'Mushroom Gathering',
    description: 'A cook needs rare mushrooms that grow near the river stones.',
    objectives: [{ id: 'gather_mushrooms', description: 'Gather mushrooms', target: 5 }],
  },
  {
    id: 'lore_fragments',
    name: 'Lost Pages of the Archive',
    description: 'Scattered lore fragments from an ancient library have been found in ruins across the region.',
    objectives: [{ id: 'collect_fragments', description: 'Collect lore fragments', target: 4 }],
  },
  {
    id: 'road_repair',
    name: 'Mend the East Road',
    description: 'Sections of the old east road have crumbled. Place stone blocks to repair the path.',
    objectives: [{ id: 'place_stones', description: 'Place cobblestone on the road', target: 20 }],
  },
  {
    id: 'troll_bounty',
    name: 'The Bridge Troll',
    description: 'A troll has claimed the old stone bridge. Defeat it to restore safe passage.',
    objectives: [{ id: 'defeat_troll', description: 'Defeat the bridge troll', target: 1 }],
  },
  {
    id: 'crafting_commission_armor',
    name: 'Armor for the Wardens',
    description: 'The road wardens need leather armor. Craft and deliver sets to their outpost.',
    objectives: [{ id: 'deliver_armor', description: 'Deliver leather armor', target: 3 }],
  },
  {
    id: 'herb_gathering_mirkwood',
    name: 'Herbs of Mirkwood',
    description: 'The Woodland Guardians need medicinal herbs that grow deep within the shadowed paths of Mirkwood.',
    factionId: 'woodland_guardians',
    reward: { xp: 120, items: [{ id: 'elven_salve', quantity: 2 }] },
    objectives: [{ id: 'gather_mirkwood_herbs', description: 'Gather rare herbs in Mirkwood', target: 8 }],
  },
  {
    id: 'goblin_camp_clear',
    name: 'Goblin Camp Assault',
    description: 'A goblin encampment has been established near the trade road. Destroy it before their numbers grow.',
    factionId: 'road_wardens',
    reward: { xp: 200, items: [{ id: 'iron_sword', quantity: 1 }] },
    objectives: [
      { id: 'defeat_camp_goblins', description: 'Defeat goblins in the camp', target: 8 },
      { id: 'destroy_camp_tents', description: 'Destroy goblin tents', target: 3 },
    ],
  },
  {
    id: 'dwarven_relic_hunt',
    name: 'Relics of the Dwarven Halls',
    description: 'Ancient relics from a collapsed dwarven hall are scattered across the mountain foothills. Recover them.',
    factionId: 'dwarven_crafters',
    reward: { xp: 180, items: [{ id: 'dwarven_ring', quantity: 1 }] },
    objectives: [{ id: 'recover_relics', description: 'Recover dwarven relics', target: 5 }],
  },
  {
    id: 'road_repair_bree',
    name: 'Mend the Bree Road',
    description: 'The road leading into Bree has deteriorated badly. Place stone and gravel to restore safe passage.',
    factionId: 'road_wardens',
    reward: { xp: 100, items: [{ id: 'stone_block', quantity: 10 }] },
    objectives: [
      { id: 'place_gravel', description: 'Place gravel on the road', target: 15 },
      { id: 'place_cobblestone', description: 'Place cobblestone markers', target: 6 },
    ],
  },
  {
    id: 'spider_nest_clear',
    name: 'Purge the Spider Nest',
    description: 'A massive spider nest threatens the southern forest paths. Burn the webs and slay the brood mother.',
    factionId: 'woodland_guardians',
    reward: { xp: 250, items: [{ id: 'spider_silk', quantity: 5 }] },
    objectives: [
      { id: 'burn_webs', description: 'Burn spider webs', target: 6 },
      { id: 'defeat_brood_mother', description: 'Defeat the brood mother', target: 1 },
    ],
  },
  {
    id: 'wolf_den_clear',
    name: 'Clear the Wolf Den',
    description: 'Wargs have established a den in the Anduin valley caves. The Beorning Wardens need help driving them out.',
    factionId: 'beorning_wardens',
    reward: { xp: 180, items: [{ id: 'wolf_pelt', quantity: 3 }] },
    objectives: [{ id: 'defeat_wargs', description: 'Defeat wargs in the den', target: 6 }],
  },
  {
    id: 'beacon_light_chain',
    name: 'Light the Beacon Chain',
    description: 'The old warning beacons along the road have gone dark. Climb to each summit and relight the fires.',
    factionId: 'road_wardens',
    reward: { xp: 160, items: [{ id: 'torch', quantity: 5 }] },
    objectives: [{ id: 'light_beacons', description: 'Light beacon fires', target: 4 }],
  },
  {
    id: 'lore_collection_rivendell',
    name: 'Lost Lore of Rivendell',
    description: 'Scattered scrolls of ancient Elven knowledge have been found in ruins. Return them to the Keepers.',
    factionId: 'rivendell_keepers',
    reward: { xp: 150, items: [{ id: 'lore_scroll', quantity: 1 }] },
    objectives: [{ id: 'collect_scrolls', description: 'Collect Elven lore scrolls', target: 6 }],
  },
  {
    id: 'smith_commission_iron',
    name: 'Iron Commission for the Smiths',
    description: 'The dwarven smiths need iron tools and fittings crafted to exact specifications.',
    factionId: 'dwarven_crafters',
    reward: { xp: 140, items: [{ id: 'dwarven_ingot', quantity: 2 }] },
    objectives: [
      { id: 'craft_iron_tools', description: 'Craft iron tools', target: 4 },
      { id: 'deliver_fittings', description: 'Deliver iron fittings', target: 3 },
    ],
  },
  {
    id: 'cook_feast_hobbit',
    name: 'Feast Preparations',
    description: 'A grand feast is being planned at the frontier settlement. Gather ingredients and prepare the dishes.',
    factionId: 'road_wardens',
    reward: { xp: 100, items: [{ id: 'feast_plate', quantity: 1 }] },
    objectives: [
      { id: 'gather_ingredients', description: 'Gather feast ingredients', target: 10 },
      { id: 'prepare_dishes', description: 'Prepare feast dishes', target: 4 },
    ],
  },
  {
    id: 'scout_mountain_pass',
    name: 'Scout the Mountain Pass',
    description: 'The Beorning Wardens need a scout to traverse the high mountain pass and report on enemy movements.',
    factionId: 'beorning_wardens',
    reward: { xp: 200, items: [{ id: 'climbing_rope', quantity: 2 }] },
    objectives: [
      { id: 'reach_summit', description: 'Reach the mountain summit', target: 1 },
      { id: 'mark_enemy_camps', description: 'Mark enemy encampments on the map', target: 3 },
    ],
  },
  {
    id: 'map_fragment_hunt',
    name: "The Cartographer's Request",
    description: 'An Elven cartographer needs old map fragments to reconstruct a complete chart of the northern wilds.',
    factionId: 'rivendell_keepers',
    reward: { xp: 130, items: [{ id: 'region_map', quantity: 1 }] },
    objectives: [{ id: 'find_map_fragments', description: 'Find map fragments in ruins', target: 5 }],
  },
  {
    id: 'ruin_survey_trollshaws',
    name: 'Survey the Trollshaws Ruins',
    description: 'Ancient structures in the Trollshaws may hold clues about the old kingdom. Survey and document them.',
    factionId: 'rivendell_keepers',
    reward: { xp: 170, items: [{ id: 'survey_notes', quantity: 1 }] },
    objectives: [{ id: 'survey_ruins', description: 'Survey ruin sites in the Trollshaws', target: 4 }],
  },
  {
    id: 'mushroom_foraging',
    name: 'Foraging in the Shire Woods',
    description: 'Rare glowing mushrooms grow in the damp hollows of the Shire woods. The Guardians use them for remedies.',
    factionId: 'woodland_guardians',
    reward: { xp: 90, items: [{ id: 'glowing_mushroom', quantity: 5 }] },
    objectives: [{ id: 'forage_mushrooms', description: 'Forage rare mushrooms', target: 8 }],
  },
  {
    id: 'guard_duty_outpost',
    name: 'Guard Duty at the Outpost',
    description: 'The road wardens are short-staffed. Stand guard at the frontier outpost through the night and repel attackers.',
    factionId: 'road_wardens',
    reward: { xp: 220, items: [{ id: 'warden_badge', quantity: 1 }] },
    objectives: [
      { id: 'survive_night', description: 'Survive the night at the outpost', target: 1 },
      { id: 'repel_attackers', description: 'Repel attacking enemies', target: 5 },
    ],
  },
];

export function getSideQuest(id) {
  return sideQuests.find(q => q.id === id);
}
